#dataset_root: /home/martinvalentine/Desktop/CSLR-VSL/data/processed/VSL_Sample/features/256x256px
dataset_root: /home/martinvalentine/Desktop/v-sign/data/interim/256x256px/VSL_V0
dict_path: /home/martinvalentine/Desktop/v-sign/data/processed/VSL_V0/gloss_dict.npy
evaluation_dir: /home/martinvalentine/Desktop/v-sign/src/vsign/evaluation/slr_eval
evaluation_prefix: vsl_v0-ground-truth